using '../main.bicep'
param vmSize = 'Standard_B2s'
param workload = 'test'
param environment = 'dev'
param resourceGroupName =  'rg-app1-dev-eastus-01'
param imageType = 'windows'
param vnetName = 'dev-vnet'
param subnetName = 'vm-dev-snet'
param vmname  = 'vm-app-04'
param computerName = 'vm-app-04'
param networkResourceGroupName = 'NW-dev-rg'
param vmAdminUserName = 'azadmin'
param vmAdminPassword = 'Chitti@8985901955'
param vmDomainJoinDomainName = 'abc.com'
param domainAdminUserName = 'admin1'
param domainAdminPassword = 'Chitti@8985901955'
param domainJoinOptions = 3
param ouPath = ''
