using '../main.bicep'
param vmSize = ''
param workload = ''
param environment = ''
param resourceGroupName =  ''
param imageType = ''
param vnetName = 'dev-vnet'
param subnetName = ''
param vmname  = ''
param computerName = ''
param networkResourceGroupName = 'NW-dev-rg'
param vmAdminUserName = 'azadmin'
param vmAdminPassword = ''
param vmDomainJoinDomainName = 'abc.com'
param domainAdminUserName = 'admin1'
param domainAdminPassword = ''
param domainJoinOptions = '3'
param ouPath = ''
