
name: azureVM-deploy
####################################################################
## Triggers
####################################################################
on:
  workflow_call:
    inputs:
      resourceGroupName:
        required: true
        description: Reaource Group Name
        type: string
      subnetName:
        required: true
        description: Subnet Name 
        type: string
      computerName:
        required: true
        description: Computer Name
        type: string
      imageType:
        required: true
        description: Virtual Machine Image Type
        type: string
      workload:
        required: true
        description: App Name
        type: string
      environment:
        required: true
        description: Environment to run this workflow
        type: string
      vmSize:
        required: true
        description: Select a VM size to support the workload that you want to run
        type: string
      location:
        required: true
        description: Azure location to carry out deployment
        type: string
      instance_count:
        required: true
        description: Two digit instance count for azure resources
        type: string

####################################################################
## Permissions
####################################################################
permissions:
  id-token: write
  contents: write
  actions: read

####################################################################
## Job
####################################################################
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      ####################################################################
      ## Login to azure
      ####################################################################
      - uses: actions/checkout@v4
      - name: Login to azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      # ####################################################################
      # ## Set Subscription
      # ####################################################################
      # - name: set azure infrastructure
      #   run: |
      #     az account set -s  ${{ inputs.subscription-id }}
      # ####################################################################
      # ## Running infrastructure validation
      # ####################################################################
      - name: Validate azure infrastructure
        run: |
          az deployment sub validate \
          --location=${{ inputs.location }} \
          --template-file infrastructure/main.bicep \
          --parameters infrastructure/params/${{ inputs.environment }}.bicepparam \
          --parameters environment=${{ inputs.environment }} \
          resourceGroupName=${{ inputs.resourceGroupName }} \
          workload=${{ inputs.workload }} \
          subnetName=${{ inputs.subnetName }} \
          vmSize=${{inputs.vmSize}} \
          vmname=vm-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }} \
          imageType=${{ inputs.imageType  }} \
          computerName=${{ inputs.computerName }} \
          vmAdminPassword=${{ secrets.vmAdminPassword }} 
          # extensionDomainJoinPassword=${{ secrets.extensionDomainJoinPassword }} \
          # extensionDomainJoinUserName=${{ vars.extensionDomainJoinUserName }} \
          # extensionDomainJoinDomainName=${{ vars.extensionDomainJoinDomainName }} 
       

      ####################################################################
      ## Deploying infrasturcture
      ####################################################################
      - name: Deploying azure infrastructure
        run: |
          az deployment sub create \
          --location=${{ inputs.location }} \
          --template-file infrastructure/main.bicep \
          --parameters infrastructure/params/${{ inputs.environment }}.bicepparam \
          --parameters environment=${{ inputs.environment }} \
          resourceGroupName=${{ inputs.resourceGroupName }} \
          workload=${{ inputs.workload }} \
          subnetName=${{ inputs.subnetName }} \
          vmSize=${{inputs.vmSize}} \
          vmname=vm-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }} \
          imageType=${{ inputs.imageType  }} \
          computerName=${{ inputs.computerName }} \
          vmAdminPassword=${{ secrets.vmAdminPassword }} 
          # extensionDomainJoinPassword=${{ secrets.extensionDomainJoinPassword }} \
          # extensionDomainJoinUserName=${{ vars.extensionDomainJoinUserName }} \
          # extensionDomainJoinDomainName=${{ vars.extensionDomainJoinDomainName }}           
       
