name: AzureVM-dev-Deploy
# Trigger the workflow when pushing to the main branch or manually via workflow dispatch
on:
  # push:
  #   branches:
  #     # - main

  workflow_dispatch:
    inputs:
      # subscription-id:
      #   required: true
      #   description: subscription-id for the deployement
      #   type: string
      # build_id:
      #  description: build workflow id to pick artifacts and deploy
      #  required: true
      resourceGroupName:
        required: true
        description: Reaource Group Name
        type: string
        default: ''
      subnetName:
        required: true
        description: Subnet Name
        type: string
        default: ''
      computerName:
        required: true
        description: Computer Name
        type: string
      imageType:
        description: 'Image Type'
        required: true
        default: windows
        type: choice
        options:
          - windows
          - linux
          - windows_domain_joined
          - linux-domain-joined
      workload:
        required: true
        description: APP Name
        type: string
        default: ''
      environment:
        required: true
        description: Environment
        type: string
        default: ''
      vmSize:
        required: true
        description: Select a VM size to support the workload that you want to run
        type: string
        default: ''
      location:
        required: true
        description: Azure location to carry out deployment
        type: choice
        default: ''
        options:
          - centralus
          - eastus
      # instance_count:
      #   required: false
      #   description: Two digit instance count for azure resources
      #   type: string
      #   default: '01'

####################################################################
## Permissions
####################################################################
permissions:
  id-token: write
  contents: write
  actions: read

####################################################################
## Jobs
####################################################################
jobs:
  deploy:
    uses: nareshyedlapalli/az-vm-deployment/.github/workflows/deploy.yml@main    
    with:
     # build_id: ${{ inputs.build_id }}
      workload: ${{ inputs.workload }}
      imageType: ${{ inputs.imageType  }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
      environment: dev
      # subscription-id: ${{ inputs.subscription-id }}
      location: ${{ inputs.location }}
      instance_count: '01'
      subnetName: ${{ inputs.subnetName }}
      vmSize: ${{inputs.vmSize}}
      computerName: ${{ inputs.computerName }}
    secrets: inherit    
