name: AzureVM-dev-Deploy
# Trigger the workflow when pushing to the main branch or manually via workflow dispatch
on:
  #push:
   # branches:
      # - main

  workflow_dispatch:
    inputs:
      # subscription-id:
      #   required: true
      #   description: subscription-id for the deployement
      #   type: string
      # build_id:
      #  description: build workflow id to pick artifacts and deploy
      #  required: true
      resourceGroupName:
        required: true
        description: Reaource Group Name
        type: string
        default: ''
      subnetName:
        required: true
        description: Subnet Name
        type: string
        default: ''
      computerName:
        required: true
        description: Computer Name
        type: string
      vmImageDetails:
        description: 'Image Type'
        required: true
        default: 'warning'
        type: choice
        options:
          - windows
          - linux
          - windows-domain-joined
          - linux-domain-joined
      workload:
        required: true
        description: APP Name
        type: string
        default: ''
      environment:
        required: true
        description: Environment
        type: string
        default: ''
      vmSize:
        required: true
        description: Select a VM size to support the workload that you want to run
        type: string
        default: ''
      location:
        required: true
        description: Azure location to carry out deployment
        type: choice
        default: ''
        options:
          - centralus
          - eastus
      # instance_count:
      #   required: false
      #   description: Two digit instance count for azure resources
      #   type: string
      #   default: '01'

####################################################################
## Permissions
####################################################################
permissions:
  id-token: write
  contents: write
  actions: read

####################################################################
## Jobs
####################################################################
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Set Image ID  
        id: set-image-id  
        run: |  
          if [[ "${{ inputs.vmImageDetails }}" == "windows" ]]; then  
            echo "::set-output name=image-id::/subscriptions/e7aab2b6-9293-4e87-a1b2-0d4bab217a10/resourceGroups/rg-app1-dev-eastus-01/providers/Microsoft.Compute/galleries/windows2022/images/windows/versions/0.0.1"  
          elif [[ "${{ inputs.vmImageDetails }}" == "linux" ]]; then  
            echo "::set-output name=image-id::/subscriptions/e7aab2b6-9293-4e87-a1b2-0d4bab217a10/resourceGroups/rg-app1-dev-eastus-01/providers/Microsoft.Compute/galleries/test/images/test/versions/0.0.2"  
          elif [[ "${{ inputs.vmImageDetails }}" == "windows-domain-joined" ]]; then  
            echo "::set-output name=image-id::/subscriptions/your-subscription-id/resourceGroups/your-resource-group/providers/Microsoft.Compute/galleries/your-gallery-name/images/windows-domain-joined/versions/your-version"  
          elif [[ "${{ inputs.vmImageDetails }}" == "linux-domain-joined" ]]; then  
            echo "::set-output name=image-id::/subscriptions/your-subscription-id/resourceGroups/your-resource-group/providers/Microsoft.Compute/galleries/your-gallery-name/images/linux-domain-joined/versions/your-version"  
          fi  
  
      - name: Deploy Azure VM  
        uses: ./.github/workflows/deploy.yml
        with:
         # build_id: ${{ inputs.build_id }}
          workload: ${{ inputs.workload }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          environment: dev
          # subscription-id: ${{ inputs.subscription-id }}
          location: ${{ inputs.location }}
          instance_count: '01'
          subnetName: ${{ inputs.subnetName }}
          vmSize: ${{inputs.vmSize}}
          computerName: ${{ inputs.computerName }}
          vmImageDetails: ${{ inputs.vmImageDetails }}
          secrets: inherit 
